version: '3.8'
services:
  apache:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./apache2.conf:/etc/apache2/apache2.conf
      - ./html:/var/www/html
    restart: always
