version: '3.8'
services:
  apache:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./html:/usr/local/apache2/htdocs
    restart: always
